version: 2
jobs:
  build:
    docker:
      - image: vvakame/review:3.1
    steps:
      - checkout
      - run:
          name: Build PDF
          command: rake clean pdf
          working_directory: ~/sample
      - store_artifacts:
          path: ~/sample/book.pdf
          destination: book.pdf
      - save_cache:
          key: build-{{ .Revision }}
          paths:
            - ~/sample
  deploy:
    docker:
      - image: circleci/golang
    working_directory: ~/deploy
    steps:
      - run: go get github.com/prasmussen/gdrive
      # 成果物をリストア
      - restore_cache:
          keys:
            - build-{{ .Revision }}
      - deploy:
          command: |
            echo $GOOGLE_SERVICE_ACCOUNT_CREDENTIAL > credential.json
            filename="~/sample/book-"$(date +%Y%m%d_%H%M%S)".pdf"
            mv ~/sample/book.pdf $filename
            gdrive --config $(pwd) --service-account credential.json upload -p ${GOOGLE_DRIVE_FOLDER} $filename

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
