version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.6.0-node-browsers
              working_directory: ~/sample
              steps:
                  - checkout
                  - run:
                      command: npm install
                  - run:
                      command: ./.circleci/review-textlint.sh
