version: 2
jobs:
  build:
    docker:
      - image: vvakame/review:3.1
      - image: circleci/golang
    steps:
      - checkout
      - run:
          name: Build PDF
          command: rake clean pdf
          working_directory: ./sample
      - run:
          name: move book
          command: |
            mkdir build
            mv ./sample/book.pdf build/
            chmod -R 777 build
      - store_artifacts:
          path: ./build/book.pdf
          destination: book.pdf
      - run: go get github.com/prasmussen/gdrive
      - deploy:
          command: |
            echo $GOOGLE_SERVICE_ACCOUNT_CREDENTIAL > credential.json
            filename="./build/book-"$(date +%Y%m%d_%H%M%S)".pdf"
            mv ./build//book.pdf $filename
            gdrive --config $(pwd) --service-account credential.json upload -p ${GOOGLE_DRIVE_FOLDER} $filename
