version: 2
jobs:
  build:
    docker:
        - image: vvakame/review:3.1
    steps:
      - checkout
      - run:
          name: Build PDF
          command: rake clean pdf
          working_directory: ./sample
      - store_artifacts:
          path: ./sample/book.pdf
          destination: book.pdf
      - run:
          name: Upload to Dropbox
          command: ./upload_dropbox.sh ./sample/book.pdf ${DROPBOX_TOKEN}

